# -*- coding: utf-8 -*-
"""desafio v1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-2RMPdsIXJ4tJC6BR4G0zOBdL2eBBqZ_
"""

menu = """
[0] Depositar
[1] Sacar
[2] Extrato
[3] Sair

=> """

saldo = 0
limite = 500
extrato = ""
numero_saques = 0
LIMITE_SAQUES = 3

while True:

  opcao = input(menu)

  if opcao == "0":
    print("\n DEPÓSITO \n")
    deposito = int(input("Insira o valor que deseja depositar: R$"))
    if deposito < 0:
      print("Não é possível depositar esse valor, por favor selecione novamente a opção desejada.")
    else:
      saldo += deposito
      extrato += f"Depósito: R${deposito:.2f}\n"
      print("O depósito foi bem-sucedido!")

  elif opcao == "1":
    print("\n SAQUE \n")
    if numero_saques >= 3:
      print("O limite de saques diários foi atingido. Por favor, volte amanhã!")
    else:
      saque = int(input("Insira o valor que deseja sacar: R$"))
      if saque > saldo:
        print("\n Operação falhou! \n Você não possui saldo suficiente!")
      elif saque > limite:
        print("\n Operação falhou! \n Você ultrapassou o limite de R$500,00 por saque. Por favor, tente novamente.")
      elif saque < 0:
        print("\n Operação falhou!")
      else:
        print("Saque realizado com sucesso!")
        numero_saques += 1
        LIMITE_SAQUES -= 1
        saldo -= saque
        extrato += f"Saque: R${saque:.2f}\n"
    if LIMITE_SAQUES == 0:
      print("Você atingiu o limite de saques diários!")

  elif opcao == "2":
    print("\n========== EXTRATO ==========")
    print("Não foram realizadas movimentações." if not extrato else extrato)
    print(f"\nSaldo: R${saldo:.2f}")
    print("=============================")

  elif opcao == "3":
    break

  else:
    print("Operação inválida, por favor selecione novamente a opção desejada.")